projet_lo07Bundle\Entity\reglement:
    type: entity
    table: null
    repositoryClass: projet_lo07Bundle\Repository\reglementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reglementLabel:
            type: string
            length: 255
    lifecycleCallbacks: {  }
