<?php

namespace projet_lo07Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * cursusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cursusRepository extends EntityRepository
{
}
