<?php

namespace projet_lo07Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * elementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class elementRepository extends EntityRepository
{
}
